version: "3.8"

services:
  frontend:
    build: ./frontend
    image: thejashari/snake-game-frontend:v1.0.0
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_SOCKET_SERVER_BASE=http://localhost:4005
      - NEXT_PUBLIC_SERVER_API_GATEWAY=http://localhost:4000

  api-gateway:
    build: ./api-gateway
    image: thejashari/snake-game-api-gateway:v1.0.0
    ports:
      - "4000:4000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - IDENTITY_SERVICE_URL=http://identity-service:4001
      - USER_SERVICE_URL=http://user-service:4002
      - LICENSE_SERVICE_URL=http://license-service:4003
      - ROOM_SERVICE_URL=http://room-service:4004
      - SOCKET_SERVICE_URL=http://socket-service:4005

  identity-service:
    build: ./identity-service
    image: thejashari/snake-game-identity-service:v1.0.0
    ports:
      - "4001:4001"
    env_file:
      - ./identity-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  user-service:
    build: ./user-service
    image: thejashari/snake-game-user-service:v1.0.0
    ports:
      - "4002:4002"
    env_file:
      - ./user-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  license-service:
    build: ./license-service
    image: thejashari/snake-game-license-service:v1.0.0
    ports:
      - "4003:4003"
    env_file:
      - ./license-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  room-service:
    build: ./room-service
    image: thejashari/snake-game-room-service:v1.0.0
    ports:
      - "4004:4004"
    env_file:
      - ./room-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  socket-service:
    build: ./socket-service
    image: thejashari/snake-game-socket-service:v1.0.0
    ports:
      - "4005:4005"
    env_file:
      - ./socket-service/.env
    environment:
      - CLIENT_URL=http://localhost:3000

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
