version: "3.8"

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "4000:4000"
    env_file:
      - ./api-gateway/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - IDENTITY_SERVICE_URL=http://identity-service:4001
      - USER_SERVICE_URL=http://user-service:4002
      - LICENSE_SERVICE_URL=http://license-service:4003
      - ROOM_SERVICE_URL=http://room-service:4004
      - SOCKET_SERVICE_URL=http://socket-service:4005

  identity-service:
    build: ./identity-service
    ports:
      - "4001:4001"
    env_file:
      - ./identity-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  user-service:
    build: ./user-service
    ports:
      - "4002:4002"
    env_file:
      - ./user-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  license-service:
    build: ./license-service
    ports:
      - "4003:4003"
    env_file:
      - ./license-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  room-service:
    build: ./room-service
    ports:
      - "4004:4004"
    env_file:
      - ./room-service/.env
    depends_on:
      - redis
      - rabbitmq
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672

  socket-service:
    build: ./socket-service
    ports:
      - "4005:4005"
    env_file:
      - ./socket-service/.env
    environment:
      - CLIENT_URL=http://localhost:3000

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
